### PR TITLE
[CD] Add doc income custom users

### PR DESCRIPTION
**Pull request by aannadi-plaid**

### CODE REVIEW

**Comment by ToddKerpelman** [comment]
Not sure if this is ready to be reviewed yet, but you should update update_dates.py to include the `paystub_and_risk_signals.json` file.

**Comment by aannadi-plaid** [comment]
@ToddKerpelman it's ready to review! updated the dates file. There's a thread that i started in #dev-rel-open with a bit more context on what this configuration will be used for :)

**Comment by phoenixy1** [comment]
This looks great! One request: would it be possible for you to add a small markdown file to this directory explaining how to use these files and linking to the docs? It could literally be like two sentences ("How to use these files.md") "To use these files, launch the Document Income Link flow in Sandbox and upload the .json file(s) when prompted to upload an income document. For more details, see [the docs](https://plaid.com/docs/income/document-income/#testing-document-income)." I know you submitted a docs PR, but we can't know that someone got to this repo via the docs, so I think it would be handy/useful to have instructions here as well.

**Comment by aannadi-plaid** [comment]
Ya defienately, let me add that

**Comment by aannadi-plaid** [comment]
@phoenixy1 Done!

**Review by phoenixy1 — APPROVED** [review]

**Pull request merged**
